// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package provider

import (
	"encoding/json"
	"fmt"
	"maps"
	"os"
	"slices"
	"strings"
	"testing"
)

// A function whose parameters are an anyOf (or oneOf) at the root, as
// Codex's codex_app automation_update, goes to Grok as an object: Grok's
// backend turns the request away otherwise ("[invalid_client_tool_schema]
// ... tool parameter root must be an object type", Fate on Discord). The
// object branches' properties are merged, $refs to $defs read, a field all
// of them require stays required, the non-object branches go. One that is
// an object already is left as it is.
// TestObjectRootKeepsOwnRequired: the root's and allOf's own required
// fields stay required beside anyOf's and oneOf's branches, which only add
// the fields they all require.
func TestObjectRootKeepsOwnRequired(t *testing.T) {
	var ps map[string]any
	if err := json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {"id": {"type": "string"}},
		"required": ["id"],
		"allOf": [{"properties": {"kind": {"type": "string"}}, "required": ["kind"]}],
		"anyOf": [
			{"type": "object", "properties": {"a": {"type": "string"}, "n": {"type": "integer"}}, "required": ["a", "n"]},
			{"type": "object", "properties": {"b": {"type": "string"}}, "required": ["b", "n", "id"]}
		]
	}`), &ps); err != nil {
		t.Fatal(err)
	}
	if !ObjectRoot(ps) {
		t.Fatal("not changed")
	}
	if got := fmt.Sprint(ps["required"]); got != "[id kind n]" {
		t.Fatalf("required = %s", got)
	}
	if props := ps["properties"].(map[string]any); len(props) != 5 {
		t.Fatalf("properties = %v", props)
	}
}

// TestObjectRootNestedUnion: Codex desktop's automation_update, whose
// parameters are zod's discriminated union on mode with the create and
// update branches each a union on kind of their own (toJSONSchema with
// reused: "ref", as ChatGPT.app 26.930 builds it; #1271). Folded to an
// object root, the nested branches' fields are kept, so a model can still
// create an automation, and a field the branches type apart (mode, kind)
// takes any of their types, not the first branch's alone; only mode,
// which every branch requires, stays required.
func TestObjectRootNestedUnion(t *testing.T) {
	b, err := os.ReadFile("testdata/codex_automation_update_schema.json")
	if err != nil {
		t.Fatal(err)
	}
	var ps map[string]any
	if err := json.Unmarshal(b, &ps); err != nil {
		t.Fatal(err)
	}
	if !ObjectRoot(ps) {
		t.Fatal("not changed")
	}
	if ps["type"] != "object" || ps["anyOf"] != nil || ps["oneOf"] != nil {
		t.Fatalf("root %v", ps)
	}
	props, _ := ps["properties"].(map[string]any)
	for _, k := range []string{"mode", "id", "name", "prompt", "rrule", "status", "kind", "projectId", "model", "targetThreadId", "executionEnvironment"} {
		if props[k] == nil {
			t.Errorf("no %s among %v", k, slices.Sorted(maps.Keys(props)))
		}
	}
	if got := fmt.Sprint(ps["required"]); got != "[mode]" {
		t.Errorf("required = %s", got)
	}
	// every mode a branch takes can still be sent
	mode, _ := json.Marshal(props["mode"])
	for _, m := range []string{`"view"`, `"delete"`, `__schema11`} {
		if !strings.Contains(string(mode), m) {
			t.Errorf("mode %s leaves out %s", mode, m)
		}
	}
	kind, _ := json.Marshal(props["kind"])
	if !strings.Contains(string(kind), "__schema7") || !strings.Contains(string(kind), "__schema12") {
		t.Errorf("kind %s", kind)
	}
}
