// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package provider

import (
	"regexp"
	"slices"
	"strings"
)

var (
	openAIFast = regexp.MustCompile(`^(gpt-|o\d)`)
	// a dated id is its model's: claude-opus-4-8-20260501
	claudeDated = regexp.MustCompile(`-\d{8}$`)
)

// claudeFastModels are the Claude models with fast mode (speed "fast",
// beta fast-mode-2026-02-01).
var claudeFastModels = []string{"claude-opus-4-8", "claude-opus-5", "claude-opus-5-5"}

// ClaudeFast reports whether a Claude model has fast mode.
func ClaudeFast(model string) bool {
	return slices.Contains(claudeFastModels, claudeDated.ReplaceAllString(strings.ToLower(model), ""))
}
