// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"encoding/json"
	"strings"
	"testing"
)

// Google's API takes a part's fields by their proto names as well
// (inline_data, mime_type, file_data, function_call), which agy and raw
// SDK calls send: read only as camelCase, an image or a PDF was left out
// and the model made up what it held (#934). The caller's own keys — a
// call's args, a declaration's schema — are kept as they were.
func TestGeminiSnakeCaseParts(t *testing.T) {
	body := `{"system_instruction":{"parts":[{"text":"be brief"}]},
	"generation_config":{"max_output_tokens":77,"thinking_config":{"thinking_level":"high"}},
	"tools":[{"function_declarations":[{"name":"read","parameters":{"type":"object","properties":{"file_path":{"type":"string"}}}}]}],
	"contents":[
		{"role":"user","parts":[{"text":"Transcribe this."},{"inline_data":{"mime_type":"image/jpeg","data":"SU1H"}},
			{"inline_data":{"mime_type":"application/pdf","data":"UERG"}},{"file_data":{"mime_type":"application/pdf","file_uri":"gs://b/doc.pdf"}}]},
		{"role":"model","parts":[{"function_call":{"id":"c1","name":"read","args":{"file_path":"/a_b"}}}]},
		{"role":"user","parts":[{"function_response":{"id":"c1","name":"read","response":{"line_count":3}}}]}]}`
	r, err := parseGemini([]byte(body))
	if err != nil {
		t.Fatal(err)
	}
	if r.System != "be brief" || r.MaxTokens != 77 || r.Effort != "high" {
		t.Fatalf("system %q, max %d, effort %q", r.System, r.MaxTokens, r.Effort)
	}
	if len(r.Tools) != 1 || !strings.Contains(string(r.Tools[0].Schema), `"file_path"`) {
		t.Fatalf("tools: %+v", r.Tools)
	}
	if len(r.Messages) != 3 {
		t.Fatalf("messages: %+v", r.Messages)
	}
	got := r.Messages[0].Parts
	if len(got) != 4 || got[1].Kind != Image || got[1].MediaType != "image/jpeg" || got[1].Data != "SU1H" ||
		got[2].Kind != File || got[2].MediaType != "application/pdf" || got[2].Data != "UERG" ||
		got[3].Kind != File || got[3].URL != "gs://b/doc.pdf" {
		t.Fatalf("the user's parts: %+v", got)
	}
	call := r.Messages[1].Parts
	if len(call) != 1 || call[0].Kind != ToolCall || call[0].Name != "read" || !strings.Contains(string(call[0].Args), `"file_path":"/a_b"`) {
		t.Fatalf("the call: %+v", call)
	}
	res := r.Messages[2].Parts
	if len(res) != 1 || res[0].Kind != ToolResult || !strings.Contains(res[0].Text, "line_count") {
		t.Fatalf("the result: %+v", res)
	}
}

// A Chat Completions file part (a PDF) is the request's file: Antigravity
// (Code Assist) is given it as inline data, where it was left out and the
// model answered as if it had read it (#934).
func TestChatFilePart(t *testing.T) {
	body := `{"model":"m","messages":[{"role":"user","content":[
		{"type":"text","text":"Transcribe every page."},
		{"type":"file","file":{"filename":"excerpt.pdf","file_data":"data:application/pdf;base64,UERG"}},
		{"type":"file","file":{"filename":"notes.pdf","file_data":"QkFSRQ=="}},
		{"type":"file","file":{"file_id":"file-abc","filename":"x.pdf"}}]}]}`
	r, err := parseChat([]byte(body))
	if err != nil {
		t.Fatal(err)
	}
	parts := r.Messages[0].Parts
	if len(parts) != 4 || parts[1].Kind != File || parts[1].MediaType != "application/pdf" || parts[1].Data != "UERG" ||
		parts[2].Kind != File || parts[2].MediaType != "application/pdf" || parts[2].Data != "QkFSRQ==" ||
		parts[3].Kind != File || parts[3].URL != "file-abc" {
		t.Fatalf("parts: %+v", parts)
	}
	var sent struct {
		Request struct {
			Contents []struct {
				Parts []map[string]json.RawMessage `json:"parts"`
			} `json:"contents"`
		} `json:"request"`
	}
	if err := json.Unmarshal(buildCodeAssist(r, "gemini-3.8-flash", "antigravity"), &sent); err != nil {
		t.Fatal(err)
	}
	if len(sent.Request.Contents) != 1 || len(sent.Request.Contents[0].Parts) != 4 ||
		!strings.Contains(string(sent.Request.Contents[0].Parts[1]["inlineData"]), `"application/pdf"`) {
		t.Fatalf("sent: %+v", sent)
	}
	// an upstream that can't carry a file is told of it, not left unaware
	if b := buildChat(r, "m", "x", false); !strings.Contains(string(b), "[attachment application/pdf]") {
		t.Fatalf("chat: %s", b)
	}
}
