// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"encoding/json"
	"github.com/aisk/cameo/llmconv/internal/provider"
	"net/http/httptest"
	"strings"
	"testing"
)

// A custom tool's call a translated vendor's model made (Codex's
// apply_patch) goes back to Codex with a ctc_ id, the one kind OpenAI takes
// for it; its call_id is the model's own.
func TestCustomToolCallHasCtcID(t *testing.T) {
	req := &Request{Model: "m", Namespaced: map[string]nsTool{"apply_patch": {Custom: true, Name: "apply_patch"}}}
	rec := httptest.NewRecorder()
	enc := encoder(provider.Responses, newSSEWriter(rec), req)
	enc.event(Event{Kind: KToolStart, ID: "p1", Name: "apply_patch"})
	enc.event(Event{Kind: KToolArgs, Text: `{"input":"*** Begin Patch"}`})
	enc.finish()
	var item map[string]any
	for _, ev := range events(rec.Body.String()) {
		if ev["type"] == "response.output_item.done" {
			item = ev["item"].(map[string]any)
		}
	}
	if id, _ := item["id"].(string); item["type"] != "custom_tool_call" || !strings.HasPrefix(id, "ctc_") || item["call_id"] != "p1" {
		t.Fatalf("streamed = %v", item)
	}

	res := Result{Parts: []Part{{Kind: ToolCall, ID: "p2", Name: "apply_patch", Args: json.RawMessage(`{"input":"x"}`)}}}
	var out struct {
		Output []map[string]any `json:"output"`
	}
	if err := json.Unmarshal(render(provider.Responses, res, req), &out); err != nil {
		t.Fatal(err)
	}
	if id, _ := out.Output[0]["id"].(string); len(out.Output) != 1 || out.Output[0]["type"] != "custom_tool_call" || !strings.HasPrefix(id, "ctc_") {
		t.Fatalf("rendered = %v", out.Output)
	}
}
