// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"encoding/json"
	"strings"
	"testing"
)

// A custom tool in a namespace of its own is called back under it, and a
// call whose arguments aren't the input object still hands its text on.
func TestCodexCustomToolNamespaced(t *testing.T) {
	r, err := parseResponses([]byte(`{"model":"m","input":"hi","tools":[
		{"type":"namespace","name":"mcp__pad","tools":[{"type":"custom","name":"write","description":"Write","format":{"type":"text"}}]},
		{"type":"custom","name":"apply_patch","description":"Patch files"}]}`))
	if err != nil {
		t.Fatal(err)
	}
	if len(r.Tools) != 2 || r.Tools[0].Name != "mcp__pad__write" || r.Tools[1].Name != "apply_patch" || strings.Contains(r.Tools[0].Description, "grammar") {
		t.Fatalf("tools: %+v", r.Tools)
	}
	item := callTo(map[string]any{"type": "function_call", "call_id": "c", "arguments": `{"input":"x"}`}, "mcp__pad__write", r.Namespaced)
	if item["type"] != "custom_tool_call" || item["name"] != "write" || item["namespace"] != "mcp__pad" || item["input"] != "x" {
		t.Fatalf("namespaced call: %v", item)
	}
	item = callTo(map[string]any{"type": "function_call", "call_id": "c", "arguments": `*** Begin Patch`}, "apply_patch", r.Namespaced)
	if item["type"] != "custom_tool_call" || item["input"] != "*** Begin Patch" || item["namespace"] != nil {
		t.Fatalf("plain call: %v", item)
	}
	item = renderCall(t, r.Namespaced)
	if item["type"] != "custom_tool_call" || item["input"] != "*** Begin Patch\n*** End Patch" {
		t.Fatalf("rendered call: %v", item)
	}
}

// renderCall is the non-streamed reply's item for a call to apply_patch.
func renderCall(t *testing.T, named map[string]nsTool) map[string]any {
	t.Helper()
	args, _ := json.Marshal(map[string]string{"input": "*** Begin Patch\n*** End Patch"})
	out := renderResponses(Result{Parts: []Part{{Kind: ToolCall, ID: "c", Name: "apply_patch", Args: args}}}, "m", named)
	var res struct {
		Output []map[string]any `json:"output"`
	}
	if err := json.Unmarshal(out, &res); err != nil || len(res.Output) != 1 {
		t.Fatalf("%v: %s", err, out)
	}
	return res.Output[0]
}
