// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"strings"
	"testing"
)

// What googleSearch found comes back as a search the client is told of,
// once, with its pages, before the stop.
func TestCodeAssistDecodesGrounding(t *testing.T) {
	var got []Event
	d := &codeAssistDecoder{}
	for _, line := range []string{
		`{"response":{"candidates":[{"content":{"role":"model","parts":[{"text":"Go 1.27.1 is the latest."}]}}]}}`,
		`{"response":{"candidates":[{"content":{"role":"model","parts":[{"text":""}]},"finishReason":"STOP",
			"groundingMetadata":{"webSearchQueries":["latest go release"],"groundingChunks":[{"web":{"uri":"https://vertexaisearch.cloud.google.com/grounding-api-redirect/a","title":"go.dev"}},{"web":{"uri":"https://vertexaisearch.cloud.google.com/grounding-api-redirect/b"}}]}}],
			"usageMetadata":{"promptTokenCount":10,"candidatesTokenCount":5}}}`,
		`{"response":{"candidates":[{"content":{"role":"model","parts":[]},"groundingMetadata":{"webSearchQueries":["latest go release"]}}]}}`,
	} {
		d.decode(line, func(ev Event) { got = append(got, ev) })
	}
	var kinds []EventKind
	var search Event
	for _, ev := range got {
		kinds = append(kinds, ev.Kind)
		if ev.Kind == KSearch {
			search = ev
		}
	}
	want := []EventKind{KStart, KText, KSearch, KStop, KUsage}
	if len(kinds) != len(want) {
		t.Fatalf("kinds = %v", kinds)
	}
	for i := range want {
		if kinds[i] != want[i] {
			t.Fatalf("kinds = %v, want %v", kinds, want)
		}
	}
	if search.Text != "latest go release" || len(search.Hits) != 2 || search.Hits[0].Title != "go.dev" ||
		search.Hits[1].Title != search.Hits[1].URL || !strings.HasSuffix(search.Hits[0].URL, "/a") {
		t.Errorf("search = %+v", search)
	}
}

// An image model on Code Assist is asked for images beside text, or it
// answers in words only.
func TestCodeAssistImageModelAsksForImages(t *testing.T) {
	r := &Request{Messages: []Message{{Role: "user", Parts: []Part{{Kind: Text, Text: "draw a cat"}}}}}
	if b := string(buildCodeAssist(r, "gemini-3.1-flash-image", "antigravity")); !strings.Contains(b, `"responseModalities":["TEXT","IMAGE"]`) {
		t.Errorf("image model: %s", b)
	}
	if b := string(buildCodeAssist(r, "gemini-3.8-flash", "antigravity")); strings.Contains(b, "responseModalities") {
		t.Errorf("text model: %s", b)
	}
}
