// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"testing"
)

// Ultra is Codex's, no API's: a model whose list says "ultra" (ChatGPT's
// lists it for Codex's picker) is sent max all the same.
func TestUltraIsSentAsMax(t *testing.T) {
	for _, c := range []struct {
		levels []string
		want   string
	}{
		{[]string{"low", "medium", "high", "xhigh", "max", "ultra"}, "max"},
		{[]string{"low", "medium", "high", "xhigh", "max"}, "max"},
		{[]string{"low", "medium", "high", "ultra"}, "high"},
		{nil, "max"},
	} {
		if got := fitEffort("ultra", c.levels); got != c.want {
			t.Errorf("fitEffort(ultra, %v) = %q, want %q", c.levels, got, c.want)
		}
	}
}
