// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"encoding/json"
	"testing"
)

// chatPrefill names DeepSeek's and Kimi's own prefill modes on their own
// APIs, and takes a relay on this machine or the LAN serving one of their
// models to front the vendor; every other Chat upstream re-answers.
func TestChatPrefill(t *testing.T) {
	for _, c := range []struct{ host, model, want string }{
		{"api.deepseek.com", "deepseek-chat", "prefix"},
		{"api.moonshot.cn", "kimi-k3", "partial"},
		{"api.moonshot.ai", "kimi-k3", "partial"},
		{"api.kimi.ai", "kimi-for-coding", "partial"},
		{"api.openai.com", "gpt-5", ""},
		{"openrouter.ai", "moonshotai/kimi-k3", ""}, // a relay elsewhere isn't taken to pass it on
		{"relay.example.com", "kimi-k3", ""},
		{"127.0.0.1:8080", "kimi-k3", "partial"},
		{"127.0.0.1:8080", "deepseek-chat", "prefix"},
		{"[::1]:8080", "kimi-k3", "partial"},
		{"192.168.1.5:8080", "kimi-k3", "partial"},
		{"localhost:8317", "kimi-for-coding", "partial"},
		{"127.0.0.1:8080", "gpt-5", ""},
	} {
		if got := chatPrefill(c.host, c.model); got != c.want {
			t.Errorf("chatPrefill(%q, %q) = %q, want %q", c.host, c.model, got, c.want)
		}
	}
}

// A Resume request's last assistant message carries the upstream's own
// prefill mark — DeepSeek's prefix, Kimi's partial — and its reasoning
// where the upstream reads reasoning_content back; an upstream without a
// mode gets neither (and is never asked to go on).
func TestBuildChatResumePrefillMarks(t *testing.T) {
	r := &Request{Resume: true, Messages: []Message{
		{Role: "user", Parts: []Part{{Kind: Text, Text: "hi"}}},
		{Role: "assistant", Parts: []Part{{Kind: Thinking, Text: "think-1"}, {Kind: Text, Text: "hel"}}},
	}}
	lastOf := func(body []byte) map[string]any {
		var v struct {
			Messages []map[string]any `json:"messages"`
		}
		if err := json.Unmarshal(body, &v); err != nil {
			t.Fatalf("built request isn't JSON: %v", err)
		}
		return v.Messages[len(v.Messages)-1]
	}
	m := lastOf(buildChat(r, "deepseek-chat", "api.deepseek.com", false))
	if m["prefix"] != true || m["reasoning_content"] != "think-1" {
		t.Errorf("DeepSeek's prefill = %v, want prefix and the reasoning", m)
	}
	m = lastOf(buildChat(r, "kimi-k3", "api.moonshot.cn", false))
	if m["partial"] != true || m["reasoning_content"] != "think-1" {
		t.Errorf("Kimi's prefill = %v, want partial and the reasoning", m)
	}
	m = lastOf(buildChat(r, "gpt-5", "api.openai.com", false))
	if m["prefix"] != nil || m["partial"] != nil || m["reasoning_content"] != nil {
		t.Errorf("an upstream without a prefill mode got one marked: %v", m)
	}
}
