// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"net"
	"strings"
)

// chatPrefill is the prefill mode of a Chat upstream at host serving
// model: DeepSeek's prefix (its own API, where the mode is served under
// /beta, with "prefix": true on the message) or Kimi's partial
// ("partial": true). Partial is a field of the message itself and prefix
// a path the relay forwards, so a relay on this machine or the LAN
// serving one of their models is taken to front the vendor, as
// geminiCompat takes one to front Gemini. "" elsewhere.
func chatPrefill(host, model string) string {
	h := strings.ToLower(host)
	switch {
	case h == "api.deepseek.com" || strings.HasSuffix(h, ".deepseek.com"):
		return "prefix"
	case strings.Contains(h, "moonshot") || strings.Contains(h, "kimi"):
		return "partial"
	}
	if s, _, err := net.SplitHostPort(h); err == nil {
		h = s
	}
	h = strings.Trim(h, "[]")
	if h != "localhost" && !strings.HasSuffix(h, ".local") {
		if ip := net.ParseIP(h); ip == nil || !ip.IsLoopback() && !ip.IsPrivate() {
			return ""
		}
	}
	switch m := strings.ToLower(model); {
	case strings.Contains(m, "deepseek"):
		return "prefix"
	case strings.Contains(m, "kimi"):
		return "partial"
	}
	return ""
}
