// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"github.com/aisk/cameo/llmconv/internal/provider"
	"testing"
)

func TestFitEffort(t *testing.T) {
	glm := []string{"low", "high", "max"}
	for _, c := range []struct {
		want   string
		levels []string
		got    string
	}{
		{"medium", glm, "high"}, // a tie goes up
		{"low", glm, "low"},
		{"xhigh", glm, "max"},
		{"max", []string{"low", "medium", "high"}, "high"},
		{"low", []string{"none", "minimal", "medium"}, "medium"},
		{"medium", nil, "medium"}, // levels not known: as asked
		{"medium", []string{"none"}, "medium"},
	} {
		if got := fitEffort(c.want, c.levels); got != c.got {
			t.Errorf("fitEffort(%q, %v) = %q, want %q", c.want, c.levels, got, c.got)
		}
	}
}

// requestEffort reads the reasoning a request asks for in each API's words.
func TestRequestEffort(t *testing.T) {
	for _, c := range []struct {
		proto provider.Protocol
		body  string
		want  string
	}{
		{provider.Chat, `{"reasoning_effort":"low"}`, "low"},
		{provider.Chat, `{"model":"m"}`, ""},
		{provider.Responses, `{"reasoning":{"effort":"xhigh","summary":"auto"}}`, "xhigh"},
		{provider.Responses, `{"reasoning":{"summary":"auto"}}`, ""},
		{provider.Anthropic, `{"thinking":{"type":"adaptive"},"output_config":{"effort":"medium"}}`, "medium"},
		{provider.Anthropic, `{"thinking":{"type":"enabled","budget_tokens":4096}}`, "low"},
		{provider.Anthropic, `{"thinking":{"type":"disabled"},"output_config":{"effort":"high"}}`, ""},
		{provider.Anthropic, `{"output_config":{"effort":"high"}}`, ""},
	} {
		if got := requestEffort(c.proto, []byte(c.body)); got != c.want {
			t.Errorf("%s %s: %q, want %q", c.proto, c.body, got, c.want)
		}
	}
}
