// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"encoding/json"
	"strings"
	"testing"
)

// calendarSchema is the schema the OpenAI SDK sends for the docs'
// CalendarEvent model: strict, every property required, nothing else
// allowed.
const calendarSchema = `{"type":"object","properties":{"name":{"title":"Name","type":"string"},"date":{"title":"Date","type":"string"},"participants":{"items":{"type":"string"},"title":"Participants","type":"array"}},"required":["name","date","participants"],"title":"CalendarEvent","additionalProperties":false}`

// sdkChatParse is the body client.chat.completions.parse(response_format=
// CalendarEvent) posts.
const sdkChatParse = `{"messages":[{"role":"system","content":"Extract the event information."},{"role":"user","content":"Alice and Bob are going to a science fair on Friday."}],"model":"%s","response_format":{"type":"json_schema","json_schema":{"schema":` + calendarSchema + `,"name":"CalendarEvent","strict":true}},"stream":false}`

func jsonOf(v any) string {
	b, _ := json.Marshal(v)
	return string(b)
}

// sameFormat is whether a and b are the same JSON value, whatever their keys'
// order.
func sameFormat(t *testing.T, a, b string) bool {
	t.Helper()
	var x, y any
	if err := json.Unmarshal([]byte(a), &x); err != nil {
		t.Fatalf("%v: %s", err, a)
	}
	if err := json.Unmarshal([]byte(b), &y); err != nil {
		t.Fatalf("%v: %s", err, b)
	}
	return jsonOf(x) == jsonOf(y)
}

// A Responses client's verbosity goes on beside its format to a Responses
// upstream, the format said once.
func TestResponsesTextKeepsVerbosityBesideFormat(t *testing.T) {
	r, err := parseResponses([]byte(`{"model":"gpt-5","input":"hi","text":{"verbosity":"low","format":{"type":"json_schema","name":"CalendarEvent","strict":true,"schema":` + calendarSchema + `}}}`))
	if err != nil {
		t.Fatal(err)
	}
	if r.Format == nil || r.Format.Name != "CalendarEvent" || r.Format.Strict == nil || !*r.Format.Strict {
		t.Fatalf("format = %+v", r.Format)
	}
	var built struct {
		Text map[string]json.RawMessage `json:"text"`
	}
	json.Unmarshal(buildResponses(r, "gpt-5", "api.openai.com", false), &built)
	if string(built.Text["verbosity"]) != `"low"` || !sameFormat(t, string(built.Text["format"]), `{"type":"json_schema","name":"CalendarEvent","strict":true,"schema":`+calendarSchema+`}`) {
		t.Fatalf("text = %v", built.Text)
	}
	// plain text is the default, and stays as it was sent
	r, _ = parseResponses([]byte(`{"model":"gpt-5","input":"hi","text":{"format":{"type":"text"}}}`))
	if r.Format != nil || string(r.Text) != `{"format":{"type":"text"}}` {
		t.Fatalf("plain text: format %+v, text %s", r.Format, r.Text)
	}
}

// Gemini's structured output (responseMimeType with responseJsonSchema)
// is read into the format, and a Gemini upstream (Code Assist, Factory's
// generateContent) is asked for one in those fields.
func TestStructuredOutputOnGemini(t *testing.T) {
	r, err := parseChat([]byte(strings.Replace(sdkChatParse, "%s", "gemini-3-flash", 1)))
	if err != nil {
		t.Fatal(err)
	}
	var built struct {
		Request struct {
			GenerationConfig map[string]json.RawMessage `json:"generationConfig"`
		} `json:"request"`
	}
	json.Unmarshal(buildCodeAssist(r, "gemini-3-flash", "gemini"), &built)
	gc := built.Request.GenerationConfig
	if string(gc["responseMimeType"]) != `"application/json"` || !sameFormat(t, string(gc["responseJsonSchema"]), calendarSchema) {
		t.Fatalf("generationConfig = %v", gc)
	}
	g, err := parseGemini([]byte(`{"contents":[{"role":"user","parts":[{"text":"Alice and Bob are going to a science fair on Friday."}]}],"generationConfig":{"responseMimeType":"application/json","responseJsonSchema":` + calendarSchema + `}}`))
	if err != nil {
		t.Fatal(err)
	}
	var chat struct {
		ResponseFormat json.RawMessage `json:"response_format"`
	}
	json.Unmarshal(buildChat(g, "gpt-4o-mini", "openrouter.ai", false), &chat)
	if !sameFormat(t, string(chat.ResponseFormat), `{"type":"json_schema","json_schema":{"name":"response","schema":`+calendarSchema+`}}`) {
		t.Fatalf("response_format = %s", chat.ResponseFormat)
	}
}
