// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"encoding/json"
	"strings"
	"testing"
)

func events(body string) []map[string]any {
	var out []map[string]any
	readSSE(strings.NewReader(body), func(_, data string) error {
		var m map[string]any
		if json.Unmarshal([]byte(data), &m) == nil {
			out = append(out, m)
		}
		return nil
	})
	return out
}

// Anthropic's input count leaves out what the prompt read from its cache
// and wrote to it; OpenAI's and Gemini's count both.
func TestUsagePromptCountsCacheWrites(t *testing.T) {
	u := Usage{Input: 2, Output: 30, CacheRead: 6176, CacheWrite: 20563}
	if r := u.responses(); r["input_tokens"] != 26741 || r["total_tokens"] != 26771 {
		t.Errorf("responses: %v", r)
	}
	if c := u.chat(); c["prompt_tokens"] != 26741 {
		t.Errorf("chat: %v", c)
	}
	if g := u.gemini(); g["promptTokenCount"] != 26741 || g["totalTokenCount"] != 26771 {
		t.Errorf("gemini: %v", g)
	}
}
