// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"encoding/base64"
	"encoding/json"
	"slices"
	"strings"
)

const (
	sigMark    = "__ts__"  // the signature's own bytes, base64url
	sigMarkRaw = "__tsr__" // a signature that isn't canonical base64, its text base64url
)

// signedID is a tool call's id carrying its thought signature.
func signedID(id, sig string) string {
	if sig == "" {
		return id
	}
	if id == "" {
		id = "call_" + newID()
	}
	if b, err := base64.StdEncoding.DecodeString(sig); err == nil && base64.StdEncoding.EncodeToString(b) == sig {
		return id + sigMark + base64.RawURLEncoding.EncodeToString(b)
	}
	return id + sigMarkRaw + base64.RawURLEncoding.EncodeToString([]byte(sig))
}

// unsignedID splits an id signedID made into the call's own id and its
// signature; any other id comes back as it is, with no signature.
func unsignedID(id string) (string, string) {
	if i := strings.Index(id, sigMarkRaw); i > 0 {
		if b, err := base64.RawURLEncoding.DecodeString(id[i+len(sigMarkRaw):]); err == nil && len(b) > 0 {
			return id[:i], string(b)
		}
	}
	if i := strings.Index(id, sigMark); i > 0 {
		if b, err := base64.RawURLEncoding.DecodeString(id[i+len(sigMark):]); err == nil && len(b) > 0 {
			return id[:i], base64.StdEncoding.EncodeToString(b)
		}
	}
	return id, ""
}

// unsignCalls takes the signatures off a parsed request's call ids: a tool
// call keeps its own id and has the signature as its Signature, a result
// answers that id. Messages are copied before they change.
func unsignCalls(r *Request) {
	for i, m := range r.Messages {
		var parts []Part
		for j, p := range m.Parts {
			switch p.Kind {
			case ToolCall:
				id, sig := unsignedID(p.ID)
				if sig == "" {
					continue
				}
				p.ID = id
				if p.Signature == "" {
					p.Signature = sig
				}
			case ToolResult:
				id, sig := unsignedID(p.CallID)
				if sig == "" {
					continue
				}
				p.CallID = id
			default:
				continue
			}
			if parts == nil {
				parts = slices.Clone(m.Parts)
			}
			parts[j] = p
		}
		if parts != nil {
			r.Messages[i].Parts = parts
		}
	}
}

// googleSignature is the thought signature in a tool call's extra_content.
func googleSignature(extra json.RawMessage) string {
	if len(extra) == 0 {
		return ""
	}
	var v struct {
		Google struct {
			ThoughtSignature string `json:"thought_signature"`
		} `json:"google"`
	}
	json.Unmarshal(extra, &v)
	return v.Google.ThoughtSignature
}

// googleExtra is extra_content carrying a thought signature.
func googleExtra(sig string) map[string]any {
	return map[string]any{"google": map[string]any{"thought_signature": sig}}
}
