// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"strings"
	"testing"
)

// An id carries any signature and gives it back exactly; one it doesn't
// carry stays as it was.
func TestSignedID(t *testing.T) {
	for _, c := range []struct{ id, sig string }{
		{"function-call-1", "CiQBjz1rX+/="},
		{"function-call-1", "c2ln"},
		{"", "c2ln"},
		{"call_x", "not base64!"},
		{"call_x", ""},
	} {
		got := signedID(c.id, c.sig)
		if strings.ContainsAny(got, "+/=! ") {
			t.Errorf("signedID(%q, %q) = %q, not an id every client takes", c.id, c.sig, got)
		}
		id, sig := unsignedID(got)
		if sig != c.sig || (c.id != "" && id != c.id) || id == "" {
			t.Errorf("signedID(%q, %q) = %q came back as %q, %q", c.id, c.sig, got, id, sig)
		}
	}
	if id, sig := unsignedID("toolu_01__ts__"); id != "toolu_01__ts__" || sig != "" {
		t.Errorf("a plain id read as %q, %q", id, sig)
	}
}
