// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"encoding/json"
	"strings"
	"testing"
)

// The thinking goes back to MiniMax where it came from, in the assistant's
// text between <think> tags, as MiniMax asks for its interleaved thinking;
// a relay serving MiniMax's models, or another model on Chat, is sent no
// thinking, as before.
func TestMiniMaxThinkingGoesBackInTags(t *testing.T) {
	r := &Request{Messages: []Message{
		{Role: "user", Parts: []Part{{Kind: Text, Text: "hi"}}},
		{Role: "assistant", Parts: []Part{{Kind: Thinking, Text: "\nThe user greets me.\n"}, {Kind: Text, Text: "Hello!"}}},
		{Role: "user", Parts: []Part{{Kind: Text, Text: "again"}}},
	}}
	for _, c := range []struct{ model, host, want string }{
		{"MiniMax-M2.7", "api.minimax.io", "<think>\nThe user greets me.\n</think>\n\nHello!"},
		{"MiniMax-M2.7", "api.minimaxi.com", "<think>\nThe user greets me.\n</think>\n\nHello!"},
		{"minimax/minimax-m3", "openrouter.ai", "Hello!"},
		{"kimi-k3", "api.moonshot.cn", "Hello!"},
	} {
		var q struct {
			Messages []map[string]any `json:"messages"`
		}
		if err := json.Unmarshal(buildChat(r, c.model, c.host, false), &q); err != nil {
			t.Fatal(err)
		}
		if got := q.Messages[1]["content"]; got != c.want {
			t.Errorf("%s at %s: assistant content %q, want %q", c.model, c.host, got, c.want)
		}
	}
}

// A <think> block at the head of a Chat reply is thinking however the tags
// fall across chunks; one later in the text, or a tag that only starts
// like it, is the answer as it came.
func TestChatThinkTags(t *testing.T) {
	run := func(parts ...string) (think, text string) {
		var d chatDecoder
		for i, p := range parts {
			ch := map[string]any{"index": 0, "delta": map[string]any{"content": p}}
			if i == len(parts)-1 {
				ch["finish_reason"] = "stop"
			}
			b, _ := json.Marshal(map[string]any{"id": "x", "choices": []any{ch}})
			d.decode(string(b), func(ev Event) {
				switch ev.Kind {
				case KThink:
					think += ev.Text
				case KText:
					text += ev.Text
				}
			})
		}
		return
	}
	for _, c := range []struct {
		name        string
		parts       []string
		think, text string
	}{
		{"whole", []string{"<think>Greeting.</think>\n\nHello"}, "Greeting.", "Hello"},
		{"one byte a chunk", strings.Split("<think>ab</think>cd", ""), "ab", "cd"},
		{"a thought's close doesn't end it", []string{"<think>a</thought>b</think>c"}, "a</thought>b", "c"},
		{"a think tag later", []string{"Hi <think>no</think>"}, "", "Hi <think>no</think>"},
		{"<thin is text", []string{"<thin", "g>"}, "", "<thing>"},
	} {
		t.Run(c.name, func(t *testing.T) {
			if think, text := run(c.parts...); think != c.think || text != c.text {
				t.Errorf("think %q text %q, want %q %q", think, text, c.think, c.text)
			}
		})
	}
}
