// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"encoding/json"
	"testing"
)

// What a Responses upstream streams of a call's arguments and what its
// finished call holds can differ; the call is given the fuller.
func TestResponsesCallArgsFromDone(t *testing.T) {
	for _, c := range []struct {
		name   string
		deltas []string
		done   string
		want   string
	}{
		{"deltas only", []string{`{"a":`, `1}`}, "", `{"a":1}`},
		{"done only", nil, `{"a":1}`, `{"a":1}`},
		{"empty deltas", []string{""}, `{"a":1}`, `{"a":1}`},
		{"redacted deltas", []string{"{}"}, `{"a":1}`, `{"a":1}`},
		{"same", []string{`{"a":`, `1}`}, `{"a":1}`, `{"a":1}`},
	} {
		t.Run(c.name, func(t *testing.T) {
			var d responsesDecoder
			lines := []string{`{"type":"response.output_item.added","item":{"type":"function_call","call_id":"c1","name":"f"}}`}
			for _, x := range c.deltas {
				q, _ := json.Marshal(x)
				lines = append(lines, `{"type":"response.function_call_arguments.delta","delta":`+string(q)+`}`)
			}
			q, _ := json.Marshal(c.done)
			lines = append(lines, `{"type":"response.output_item.done","item":{"type":"function_call","call_id":"c1","name":"f","arguments":`+string(q)+`}}`,
				`{"type":"response.completed","response":{"status":"completed"}}`)
			var col collector
			for _, l := range lines {
				d.decode(l, col.add)
			}
			res := col.finish()
			if len(res.Parts) != 1 || string(res.Parts[0].Args) != c.want || res.Stop != "tool" {
				t.Fatalf("parts %+v stop %q", res.Parts, res.Stop)
			}
		})
	}
}
