// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"bytes"
	"encoding/json"
	"testing"
)

func TestOrphanToolOutputsContentAndNoops(t *testing.T) {
	for _, body := range []string{`not json`, `{}`, `{"input":"hello"}`, `{"input":[{"type":"function_call_output","call_id":"paired","output":"ok"}]}`, `{"input":[{"role":"user","content":"ordinary"}]}`} {
		if got := orphanedToolOutputs([]byte(body)); string(got) != body {
			t.Fatalf("unchanged input rewritten: %s", got)
		}
	}
	body := []byte(`{"model":"fake/m1","previous_response_id":"resp_synthetic","input":[{"type":"function_call_output","output":[{"type":"text","text":"look"},{"type":"input_image","image_url":"data:image/png;base64,AQID"}]},{"type":"function_call_output","output":""}]}`)
	original := bytes.Clone(body)
	fixed := orphanedToolOutputs(body)
	if !bytes.Equal(body, original) {
		t.Fatal("mutated caller's request buffer")
	}
	var q struct {
		Previous string `json:"previous_response_id"`
		Input    []struct {
			Content []map[string]any `json:"content"`
		} `json:"input"`
	}
	if err := json.Unmarshal(fixed, &q); err != nil {
		t.Fatal(err)
	}
	if q.Previous != "resp_synthetic" || len(q.Input) != 2 || len(q.Input[0].Content) != 2 {
		t.Fatalf("lost context: %s", fixed)
	}
	if q.Input[0].Content[0]["text"] != "look" || q.Input[0].Content[1]["image_url"] != "data:image/png;base64,AQID" || q.Input[1].Content[0]["text"] != "Tool result received." {
		t.Fatalf("lost output content: %s", fixed)
	}
	if !bytes.Equal(orphanedToolOutputs(fixed), fixed) {
		t.Fatal("normalization is not idempotent")
	}
}
