// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"encoding/json"
	"github.com/aisk/cameo/llmconv/internal/provider"
	"testing"
)

// thoughtChat is a fast request with an assistant turn that reasoned, and
// chatBody the chat request built of it for host.
var thoughtChat = &Request{Fast: true, Messages: []Message{
	{Role: "user", Parts: []Part{{Kind: Text, Text: "hi"}}},
	{Role: "assistant", Parts: []Part{{Kind: Thinking, Text: "pondered"}, {Kind: Text, Text: "hello"}}},
	{Role: "user", Parts: []Part{{Kind: Text, Text: "again"}}},
}}

func chatBody(t *testing.T, host string) map[string]any {
	t.Helper()
	var m map[string]any
	if err := json.Unmarshal(buildChat(thoughtChat, "m", host, false), &m); err != nil {
		t.Fatal(err)
	}
	return m
}

// Cursor moved onto its plugin is told fast mode as the built-in told
// Cursor: its plugin reads the chat request's service_tier. No other
// chat upstream is told it.
func TestCursorPluginFast(t *testing.T) {
	if m := chatBody(t, "cursor"); m["service_tier"] != "priority" {
		t.Errorf("Cursor's plugin wasn't told fast: %v", m["service_tier"])
	}
	for _, host := range []string{"api.openai.com", "openrouter.ai", "zed", "api.deepseek.com", provider.CommandCodePlanID} {
		if m := chatBody(t, host); m["service_tier"] != nil {
			t.Errorf("%s was told a service tier", host)
		}
	}
}

// A Command Code Go conversation moved onto its plugin keeps its
// reasoning, as the built-in replayed it to /alpha/generate: its plugin
// reads reasoning_content. DeepSeek still gets it, others don't.
func TestCommandCodePluginReasoning(t *testing.T) {
	reasoning := func(host string) any {
		return chatBody(t, host)["messages"].([]any)[1].(map[string]any)["reasoning_content"]
	}
	for _, host := range []string{provider.CommandCodePlanID, "api.deepseek.com"} {
		if got := reasoning(host); got != "pondered" {
			t.Errorf("%s got reasoning %v", host, got)
		}
	}
	for _, host := range []string{"api.openai.com", "cursor", "zed"} {
		if got := reasoning(host); got != nil {
			t.Errorf("%s got reasoning_content %v", host, got)
		}
	}
}
