// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"encoding/json"
	"strings"
	"testing"
)

// What Chat Completions vendors and relays say was read from, or written
// to, their cache, whichever names they give it.
func TestChatUsageCache(t *testing.T) {
	for _, c := range []struct {
		name, usage string
		want        Usage
	}{
		{"openai", `{"prompt_tokens":1000,"completion_tokens":5,"prompt_tokens_details":{"cached_tokens":800}}`, Usage{Input: 200, Output: 5, CacheRead: 800}},
		{"deepseek", `{"prompt_tokens":1000,"completion_tokens":5,"prompt_cache_hit_tokens":900,"prompt_cache_miss_tokens":100}`, Usage{Input: 100, Output: 5, CacheRead: 900}},
		{"deepseek both", `{"prompt_tokens":1000,"completion_tokens":5,"prompt_cache_hit_tokens":900,"prompt_tokens_details":{"cached_tokens":900}}`, Usage{Input: 100, Output: 5, CacheRead: 900}},
		{"moonshot", `{"prompt_tokens":1000,"completion_tokens":5,"cached_tokens":600}`, Usage{Input: 400, Output: 5, CacheRead: 600}},
		{"openrouter", `{"prompt_tokens":1000,"completion_tokens":5,"prompt_tokens_details":{"cached_tokens":0,"cache_write_tokens":700}}`, Usage{Input: 300, Output: 5, CacheWrite: 700}},
		{"claude relay, whole", `{"prompt_tokens":1000,"completion_tokens":5,"cache_read_input_tokens":800,"cache_creation_input_tokens":100}`, Usage{Input: 100, Output: 5, CacheRead: 800, CacheWrite: 100}},
		{"claude relay, Anthropic's count", `{"prompt_tokens":10,"completion_tokens":5,"cache_read_input_tokens":800,"cache_creation_input_tokens":100}`, Usage{Input: 10, Output: 5, CacheRead: 800, CacheWrite: 100}},
		{"none", `{"prompt_tokens":1000,"completion_tokens":5}`, Usage{Input: 1000, Output: 5}},
	} {
		var u cUsage
		if err := json.Unmarshal([]byte(c.usage), &u); err != nil {
			t.Fatal(err)
		}
		if got := u.usage(); got != c.want {
			t.Errorf("%s: %+v, want %+v", c.name, got, c.want)
		}
	}
}

// A Codex request sent to Claude is marked for Anthropic's prompt cache:
// its instructions, and its conversation at the last block that can be.
func TestAnthropicPromptCache(t *testing.T) {
	r, err := parseResponses([]byte(`{"model":"m","instructions":"be brief","stream":true,
	  "tools":[{"type":"function","name":"shell","parameters":{"type":"object"}}],
	  "input":[{"type":"message","role":"user","content":[{"type":"input_text","text":"list files"}]},
	    {"type":"function_call","call_id":"c1","name":"shell","arguments":"{\"cmd\":\"ls\"}"},
	    {"type":"function_call_output","call_id":"c1","output":"a.go b.go"}]}`))
	if err != nil {
		t.Fatal(err)
	}
	var out struct {
		System []aBlock `json:"system"`
		Tools  []map[string]any
		Msgs   []struct{ Content []aBlock } `json:"messages"`
	}
	b := buildAnthropic(r, "claude-sonnet-5")
	json.Unmarshal(b, &out)
	if len(out.System) != 1 || out.System[0].Text != "be brief" || out.System[0].CacheControl["type"] != "ephemeral" {
		t.Fatalf("system: %s", b)
	}
	last := out.Msgs[len(out.Msgs)-1].Content
	if lb := last[len(last)-1]; lb.Type != "tool_result" || lb.CacheControl["type"] != "ephemeral" {
		t.Fatalf("last block: %s", b)
	}
	if n := strings.Count(string(b), `"cache_control"`); n != 2 {
		t.Fatalf("%d marks: %s", n, b)
	}

	// no system prompt: the tools are marked instead; thinking never is
	r.System = ""
	r.Messages = append(r.Messages, Message{Role: "assistant", Parts: []Part{{Kind: Text, Text: "done"}, {Kind: Thinking, Text: "hm", Signature: "sig"}}})
	b = buildAnthropic(r, "claude-sonnet-5")
	out.System, out.Tools, out.Msgs = nil, nil, nil
	json.Unmarshal(b, &out)
	last = out.Msgs[len(out.Msgs)-1].Content
	if out.System != nil || out.Tools[0]["cache_control"] == nil || last[1].Type != "thinking" || last[1].CacheControl != nil || last[0].CacheControl == nil {
		t.Fatalf("no system: %s", b)
	}
	if n := strings.Count(string(b), `"cache_control"`); n != 2 {
		t.Fatalf("%d marks: %s", n, b)
	}
}
