// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"testing"
)

// OpenAI's safety filter refusing a Codex turn, as the ChatGPT backend said
// it to Koohoko (#248): a 400 invalid_request_error with code bio_policy.
const bioPolicy = `{"error":{"type":"invalid_request_error","code":"bio_policy","message":"This content was flagged for possible biological risk. If this seems wrong, try rephrasing your request.","param":null}}`

// Which errors are the safety filter's, and which are the request's own.
func TestPolicyRefusalShapes(t *testing.T) {
	for body, want := range map[string]bool{
		bioPolicy: true,
		`{"type":"invalid_request_error","code":"bio_policy","message":"flagged"}`:                                                           true,
		`{"error":{"code":"cyber_policy","message":"x"}}`:                                                                                    true,
		`{"error":{"code":"content_filter","message":"The response was filtered","innererror":{"code":"ResponsibleAIPolicyViolation"}}}`:     true,
		`{"error":{"code":"invalid_prompt","message":"Invalid prompt: your prompt was flagged as potentially violating our usage policy."}}`: true,
		`{"error":{"code":"invalid_prompt","message":"Invalid prompt: missing field"}}`:                                                      false,
		`{"error":{"type":"invalid_request_error","message":"max_tokens: too large"}}`:                                                       false,
		`not json`: false,
	} {
		if _, got := policyRefusal([]byte(body)); got != want {
			t.Errorf("%s: %v", body, got)
		}
	}
}
