// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

// usageEncoder reads the encoder's chosen ID after it starts writing. Upstream
// IDs can be absent or acquire a protocol prefix, so KStart.MsgID is not enough.
// In multi-round replies the encoder keeps the single client response ID.
type usageEncoder struct {
	streamEncoder
	usage *Usage
}

func (e *usageEncoder) capture() {
	var id string
	switch enc := e.streamEncoder.(type) {
	case *responsesEncoder:
		id = enc.id
	case *anthropicEncoder:
		id = enc.id
	case *chatEncoder:
		id = enc.id
	case *geminiEncoder:
		id = enc.id
	}
	if id != "" {
		e.usage.ResponseID = id
	}
}

func (e *usageEncoder) event(ev Event) {
	e.streamEncoder.event(ev)
	e.capture()
}

func (e *usageEncoder) finish() {
	e.streamEncoder.finish()
	e.capture()
}
