// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"encoding/json"
	"testing"
)

// Neither goes to an API of another kind: Chat and Anthropic turn away a
// field they don't know.
func TestClientMetadataOnlyToResponses(t *testing.T) {
	r, err := parseResponses([]byte(`{"model":"m","input":"hi","client_metadata":{"a":"b"},"text":{"verbosity":"low"}}`))
	if err != nil {
		t.Fatal(err)
	}
	for name, b := range map[string][]byte{"chat": buildChat(r, "m", "relay.example", false), "anthropic": buildAnthropic(r, "m")} {
		var m map[string]any
		json.Unmarshal(b, &m)
		if _, ok := m["client_metadata"]; ok {
			t.Errorf("%s got client_metadata: %s", name, b)
		}
		if _, ok := m["text"]; ok {
			t.Errorf("%s got text: %s", name, b)
		}
	}
	r, _ = parseResponses([]byte(`{"model":"m","input":"hi","client_metadata":null}`))
	var m map[string]any
	json.Unmarshal(buildResponses(r, "m", "relay.example", false), &m)
	if _, ok := m["client_metadata"]; ok {
		t.Errorf("a null client_metadata went on: %v", m)
	}
}
