// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"encoding/json"
	"slices"
	"testing"
)

// #315: a Responses request rebuilt by magpie asks for what its client's
// include did, as prompt_cache_key goes on: a strict Codex relay refuses
// one without reasoning.encrypted_content. magpie's own search sources are
// added to it once.
func TestResponsesKeepsInclude(t *testing.T) {
	include := func(body, host string) []string {
		t.Helper()
		r, err := parseResponses([]byte(body))
		if err != nil {
			t.Fatal(err)
		}
		var q struct {
			Include []string `json:"include"`
		}
		json.Unmarshal(buildResponses(r, "m", host, false), &q)
		return q.Include
	}
	for _, c := range []struct {
		name, body, host string
		want             []string
	}{
		{"sealed reasoning", `{"model":"m","input":"hi","reasoning":{"effort":"low"},"include":["reasoning.encrypted_content"]}`, "relay.example", []string{"reasoning.encrypted_content"}},
		{"with search sources", `{"model":"m","input":"hi","reasoning":{"effort":"low"},"include":["reasoning.encrypted_content"],"tools":[{"type":"web_search"}]}`, "relay.example",
			[]string{"reasoning.encrypted_content", "web_search_call.action.sources"}},
		{"sources once", `{"model":"m","input":"hi","include":["web_search_call.action.sources","web_search_call.action.sources"],"tools":[{"type":"web_search"}]}`, "relay.example",
			[]string{"web_search_call.action.sources"}},
		{"xAI keeps the client's only", `{"model":"m","input":"hi","reasoning":{"effort":"low"},"include":["reasoning.encrypted_content"],"tools":[{"type":"web_search"}]}`, "api.x.ai",
			[]string{"reasoning.encrypted_content"}},
		// OpenAI refuses sealed reasoning of a model that isn't reasoning
		{"no reasoning, no sealed reasoning", `{"model":"m","input":"hi","include":["reasoning.encrypted_content","message.output_text.logprobs"]}`, "relay.example",
			[]string{"message.output_text.logprobs"}},
		{"none", `{"model":"m","input":"hi"}`, "relay.example", nil},
	} {
		if got := include(c.body, c.host); !slices.Equal(got, c.want) {
			t.Errorf("%s: include %q, want %q", c.name, got, c.want)
		}
	}
}
