// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"encoding/json"
	"github.com/aisk/cameo/llmconv/internal/provider"
	"strings"
	"testing"
)

// Anthropic's own search, streamed: its server tool's input is no call of
// the client's.
func TestAnthropicServerToolLeftOut(t *testing.T) {
	dec := decoder(provider.Anthropic)
	var got []string
	for _, d := range []string{
		`{"type":"message_start","message":{"id":"m","model":"x","usage":{"input_tokens":3}}}`,
		`{"type":"content_block_start","index":0,"content_block":{"type":"server_tool_use","id":"s","name":"web_search"}}`,
		`{"type":"content_block_delta","index":0,"delta":{"type":"input_json_delta","partial_json":"{\"query\":\"go\"}"}}`,
		`{"type":"content_block_stop","index":0}`,
		`{"type":"content_block_start","index":1,"content_block":{"type":"web_search_tool_result","tool_use_id":"s","content":[]}}`,
		`{"type":"content_block_stop","index":1}`,
		`{"type":"content_block_start","index":2,"content_block":{"type":"text","text":""}}`,
		`{"type":"content_block_delta","index":2,"delta":{"type":"text_delta","text":"Go 1.27.1"}}`,
		`{"type":"message_delta","delta":{"stop_reason":"end_turn"},"usage":{"output_tokens":4}}`,
	} {
		dec(d, func(ev Event) {
			switch ev.Kind {
			case KToolStart, KToolArgs:
				got = append(got, "tool")
			case KText:
				got = append(got, ev.Text)
			}
		})
	}
	if strings.Join(got, "|") != "Go 1.27.1" {
		t.Fatalf("%q", got)
	}
}

// Claude Code with ENABLE_TOOL_SEARCH defers WebSearch and loads it by a
// ToolSearch whose result is a tool_reference: the model elsewhere is told
// the tool is there, and the placeholder that keeps deferring on is dropped.
func TestToolSearchReferenceIsTold(t *testing.T) {
	body := `{"model":"m","max_tokens":10,"tools":[
		{"name":"ToolSearch","input_schema":{"type":"object"}},
		{"name":"WebSearch","input_schema":{"type":"object"},"defer_loading":true},
		{"name":"DeferredToolPlaceholder","input_schema":{"type":"object"},"defer_loading":true}],
		"messages":[{"role":"user","content":"search"},
		{"role":"assistant","content":[{"type":"tool_use","id":"t1","name":"ToolSearch","input":{"query":"select:WebSearch"}}]},
		{"role":"user","content":[{"type":"tool_result","tool_use_id":"t1","content":[{"type":"tool_reference","tool_name":"WebSearch"}]}]}]}`
	r, err := parseAnthropic([]byte(body))
	if err != nil {
		t.Fatal(err)
	}
	var names []string
	for _, tl := range r.Tools {
		names = append(names, tl.Name)
	}
	if strings.Join(names, ",") != "ToolSearch,WebSearch" {
		t.Fatalf("tools = %v", names)
	}
	if got := r.Messages[2].Parts[0].Text; !strings.Contains(got, "WebSearch is loaded") {
		t.Fatalf("tool result = %q", got)
	}
}

func TestSearchToldAsAnthropics(t *testing.T) {
	res := Result{Parts: []Part{{Kind: Search, Text: "go", Hits: []Hit{{Title: "Go", URL: "https://go.dev/"}}}, {Kind: Text, Text: "1.27"}}}
	var out struct {
		Content []struct {
			Type      string         `json:"type"`
			ID        string         `json:"id"`
			ToolUseID string         `json:"tool_use_id"`
			Input     map[string]any `json:"input"`
			Content   []Hit          `json:"content"`
		} `json:"content"`
	}
	json.Unmarshal(renderAnthropic(res, "m"), &out)
	c := out.Content
	if len(c) != 3 || c[0].Type != "server_tool_use" || c[0].Input["query"] != "go" || c[1].Type != "web_search_tool_result" ||
		c[1].ToolUseID != c[0].ID || len(c[1].Content) != 1 || c[1].Content[0].URL != "https://go.dev/" || c[2].Type != "text" {
		t.Fatalf("%+v", out)
	}

	// a Responses provider's own search, with the pages it found
	var events []Event
	d := &responsesDecoder{}
	d.decode(`{"type":"response.output_item.done","item":{"type":"web_search_call","status":"completed","action":{"type":"search","query":"bun","sources":[{"type":"url","url":"https://bun.com/"}]}}}`,
		func(ev Event) { events = append(events, ev) })
	if len(events) != 1 || events[0].Kind != KSearch || events[0].Text != "bun" || len(events[0].Hits) != 1 || events[0].Hits[0].URL != "https://bun.com/" {
		t.Fatalf("%+v", events)
	}
}
