// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"bytes"
	"fmt"
	"testing"
)

func TestStandalonePlainEncoding(t *testing.T) {
	for _, kind := range []string{"function_call_output", "custom_tool_call_output"} {
		for _, body := range []string{`{ "z": "<keep>&", "input": [ { "role": "user", "content": "hi" } ], "a": 1 }`, fmt.Sprintf(`{ "input": [{"type":%q,"call_id":"A","output":"<paired>"}], "instructions":"<keep>&" }`, kind)} {
			if got := orphanedToolOutputs([]byte(body)); string(got) != body {
				t.Fatalf("no-op bytes changed: %s", got)
			}
		}
		body := []byte(fmt.Sprintf(`{ "z": 1, "instructions": "<keep>&", "input": [{"type":%q,"output":"<notice>&"}], "a": 2 }`, kind))
		got := orphanedToolOutputs(body)
		for _, literal := range []string{"<keep>&", "<notice>&"} {
			if !bytes.Contains(got, []byte(literal)) {
				t.Fatalf("escaped %s: %s", literal, got)
			}
		}
		if !bytes.Equal(got, orphanedToolOutputs(got)) {
			t.Fatal("not idempotent")
		}
	}
}
