// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

import (
	"encoding/json"
	"github.com/aisk/cameo/llmconv/internal/provider"
	"net/http/httptest"
	"strings"
	"testing"
)

// A Codex turn with its tool search (#258), as Codex 0.159 sends it: the
// search in the tools, and in the input a search the model made, the tools
// it found (an MCP server's, as a namespace, deferred), and a call to one.
const searchTools = `"tools":[
	{"type":"function","name":"exec_command","parameters":{"type":"object"}},
	{"type":"tool_search","execution":"client","description":"# Tool discovery\nSearches over deferred tool metadata.","parameters":{"type":"object","properties":{"query":{"type":"string"},"limit":{"type":"number"}},"required":["query"],"additionalProperties":false}}
]`

const searchInput = `"input":[
	{"type":"message","role":"user","content":[{"type":"input_text","text":"make a calendar event"}]},
	{"type":"tool_search_call","call_id":"s1","execution":"client","arguments":{"query":"calendar create","limit":2}},
	{"type":"tool_search_output","call_id":"s1","status":"completed","execution":"client","tools":[
		{"type":"namespace","name":"mcp__cal","description":"Calendar","tools":[
			{"type":"function","name":"create_event","description":"Create a calendar event.","defer_loading":true,"parameters":{"type":"object","properties":{"title":{"type":"string"}}}}]}]},
	{"type":"function_call","call_id":"c1","namespace":"mcp__cal","name":"create_event","arguments":"{\"title\":\"x\"}"},
	{"type":"function_call_output","call_id":"c1","output":"created"}
]`

// A model magpie translates for is offered the search as a function and,
// once it has searched, the tools found; the search and its result read as
// a call and its result.
func TestToolSearchTranslated(t *testing.T) {
	r, err := parseResponses([]byte(`{"model":"m",` + searchTools + `,` + searchInput + `}`))
	if err != nil {
		t.Fatal(err)
	}
	var names []string
	for _, tl := range r.Tools {
		names = append(names, tl.Name)
	}
	if got := strings.Join(names, ","); got != "exec_command,tool_search,mcp__cal__create_event" {
		t.Fatalf("tools = %s", got)
	}
	if !strings.Contains(string(r.Tools[1].Schema), "query") || !strings.Contains(r.Tools[1].Description, "Tool discovery") {
		t.Fatalf("tool_search offered as %+v", r.Tools[1])
	}
	if !r.Namespaced["tool_search"].Search || r.Namespaced["mcp__cal__create_event"] != (nsTool{Namespace: "mcp__cal", Name: "create_event"}) {
		t.Fatalf("named = %+v", r.Namespaced)
	}
	var calls, results []Part
	for _, m := range r.Messages {
		for _, p := range m.Parts {
			switch p.Kind {
			case ToolCall:
				calls = append(calls, p)
			case ToolResult:
				results = append(results, p)
			}
		}
	}
	if len(calls) != 2 || calls[0].Name != "tool_search" || calls[0].ID != "s1" || !strings.Contains(string(calls[0].Args), `"calendar create"`) ||
		calls[1].Name != "mcp__cal__create_event" {
		t.Fatalf("calls = %+v", calls)
	}
	if len(results) != 2 || results[0].CallID != "s1" || !strings.Contains(results[0].Text, "mcp__cal__create_event") {
		t.Fatalf("results = %+v", results)
	}
}

// The model's call to the search goes back to Codex as the
// tool_search_call Codex runs, with its arguments as an object.
func TestToolSearchCallStreamedAndRendered(t *testing.T) {
	req := &Request{Model: "m", Namespaced: map[string]nsTool{"tool_search": {Search: true}}}
	rec := httptest.NewRecorder()
	enc := encoder(provider.Responses, newSSEWriter(rec), req)
	enc.event(Event{Kind: KToolStart, ID: "s2", Name: "tool_search"})
	enc.event(Event{Kind: KToolArgs, Text: `{"query":"calendar"}`})
	enc.finish()
	var items []map[string]any
	for _, ev := range events(rec.Body.String()) {
		switch ev["type"] {
		case "response.output_item.added", "response.output_item.done":
			items = append(items, ev["item"].(map[string]any))
		case "response.function_call_arguments.done":
			t.Fatalf("function arguments for the search: %v", ev)
		}
	}
	if len(items) != 2 {
		t.Fatalf("items = %v", items)
	}
	done := items[1]
	args, _ := done["arguments"].(map[string]any)
	if done["type"] != "tool_search_call" || done["execution"] != "client" || done["call_id"] != "s2" || args["query"] != "calendar" || done["name"] != nil {
		t.Fatalf("streamed = %v", done)
	}
	if items[0]["type"] != "tool_search_call" {
		t.Fatalf("added = %v", items[0])
	}

	res := Result{Parts: []Part{{Kind: ToolCall, ID: "s3", Name: "tool_search", Args: json.RawMessage(`{"query":"mail"}`)}}}
	var out struct {
		Output []map[string]any `json:"output"`
	}
	if err := json.Unmarshal(render(provider.Responses, res, req), &out); err != nil {
		t.Fatal(err)
	}
	if len(out.Output) != 1 || out.Output[0]["type"] != "tool_search_call" || out.Output[0]["arguments"].(map[string]any)["query"] != "mail" {
		t.Fatalf("rendered = %v", out.Output)
	}
}
