// Code generated by llmconv/internal/sync from github.com/yetone/magpie@acdaa28aa10cf4835b42070327efa96713f85db2. DO NOT EDIT.

package llmconv

const (
	pngA = "aGVsbG8="     // what a screenshot tool returns, inline
	pngB = "d29ybGQhIQ==" // a second one
)
